name: Test and build dyn-wall-rs for Linux and Windows  
on:
  push:
    tags:
      - "v*"
        
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Cache Deps
      uses: actions/cache@v2.0.0
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      
  release-linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Cache Deps
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Build
        run: cargo build --release
        
      - name: Copy binary over
        run: cp target/release/dyn-wall-rs .
        
      - name: Pack into tarball
        run: tar -czvf dyn-wall-rs-linux.tar.gz dyn-wall-rs
        
      - name: Find sha265sum
        run: sha256sum dyn-wall-rs-linux.tar.gz > dyn-wall-rs-linux.sha256
        
      - name: Upload Linux zip
        id: upload-linux-zip 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dyn-wall-rs-linux.tar.gz
          asset_name: dyn-wall-rs-linux.tar.gz
          asset_content_type: application/zip

      - name: Upload Linux sha256
        id: upload-linux-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: dyn-wall-rs-linux.sha256
          asset_name: dyn-wall-rs-linux.sha256
          asset_content_type: application/zip
            
  release-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Cache Deps
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release
        
      - name: Copy .exe over
        run: Copy-Item -Path target\release\dyn-wall-rs.exe
        
      - name: zip .exe
        run: tar.exe -a -cf dyn-wall-rs-windows.zip dyn-wall-rs.exe
        
      - name: Find sha265sum
        run: Get-FileHash dyn-wall-rs-windows.zip -Algorithm SHA256 | Format-List > dyn-wall-rs-windows.sha256
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload Windows zip
        id: upload-windows-zip 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        with:
          upload_url: ${{ release-linux.steps.create_release.outputs.upload_url }} 
          asset_path: dyn-wall-rs-windows.zip
          asset_name: dyn-wall-rs-windows.zip
          asset_content_type: application/zip
  
      - name: Upload Windows sha256
        id: upload-windows-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        with:
          upload_url: ${{ release-linux.steps.create_release.outputs.upload_url }} 
          asset_path: dyn-wall-rs-windows.sha256
          asset_name: dyn-wall-rs-windows.sha256
          asset_content_type: application/zip
